config/routes.rb
BloccitR4::Application.routes.draw do
  get "comments/new"
  devise_for :users
  resources :users, only: [:update]

  resources :topics do
  	resources :posts, except: [:index] do
  		resources :comments, only: [:create, :destroy]
             get '/up-vote' => 'votes#up_vote', as: :up_vote
             get '/down-vote' => 'votes#down_vote', as: :down_vote
             resources :favorites, only: [:create, :destroy]
  	end
  end

  match "about", to: 'welcome#about', via: :get

  root to: 'welcome#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	has_many :votes, dependent: :destroy
 	has_many :favorites, dependent: :destroy
	belongs_to :user
	belongs_to :topic
 	mount_uploader :image, ImageUploader

	default_scope { order('rank DESC') }

	validates :title, length: { minimum: 5 }, presence: true
	validates :body, length: { minimum: 20 }, presence: true
	# validates :topic_id, presence: true
	validates :user, presence: true

	def up_votes
		self.votes.where(value: 1).count
	end

	def down_votes
		self.votes.where(value: -1).count
	end

	def points
		self.votes.sum(:value).to_i
	end

	def update_rank
		age = (self.created_at - Time.new(1970,1,1)) / 86400
		new_rank = points + age

		self.update_attribute(:rank, new_rank)
	end

	private

	# Automatically up vote a post by the user who creates it
	def create_vote
		user.votes.create(value: 1, post: self)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @topic = Topic.find(params[:topic_id])
    authorize @topic
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = Comment.new
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
    authorize @post
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = current_user.posts.build(post_params)
    @post.topic = @topic

    authorize @post

    if @post.save
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
    if @post.update_attributes(post_params)
    	flash[:notice] = "Post was saved."
    	redirect_to [@topic, @post]
    else
    	flash[:error] = "There was an error saving the post. Please try again."
    	render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])

    title = @post.title
    authorize @post
    if @post.destroy
      flash[:notice] = "\"#{title}\" was deleted successfully."
      redirect_to @topic
    else
      flash[:error] = "There was an error deleting the post."
      render :show
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for [topic, post] do |f| %>
  <% if post.errors.any? %>
    <div class="alert alert-danger">
      <h4>There are <%= pluralize(post.errors.count, "error") %>.</h4>
      <ul>
        <% post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(post.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
  <% end %>
  <%= form_group_tag(post.errors[:body]) do %>
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
  <% end %>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<div class="row">
	<div class="col-md-4">
		<p>Guidelines for posts</p>
		<ul>
			<li>Make sure the it rhymes.</li>
			<li>Don't use the letter "A".</li>
			<li>The incessant use of hashtags will get you banned.</li>
		</ul>
	</div>
	<div class="col-md-8">
		<%= render partial: 'form', locals: { topic: @topic, post: @post } %>
	</div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<div class="row">
	<div class="col-md-4">
		<p>Guidelines for posts</p>
		<ul>
			<li>Make sure the it rhymes.</li>
			<li>Don't use the letter "A".</li>
			<li>The incessant use of hashtags will get you banned.</li>
		</ul>
	</div>
	<div class="col-md-8">
		<%= render partial: 'form', locals: { topic: @topic, post: @post } %>
	</div>
</div>

app/views/posts/show.html.erb
<div class="row">
	<div class="col-md-8">
		<%= render partial: 'votes/voter', locals: { topic: @topic, post: @post } %>
		<h1><%= markdown @post.title %></h1>
		<small>
			<%= image_tag(@post.user.avatar.tiny.url) if @post.user.avatar? %>
			submitted <%= time_ago_in_words(@post.created_at) %> ago by
			<%= @post.user.name %>
		</small>
		<p><%= markdown @post.body %></p>
		<p><%= image_tag(@post.image_url) if @post.image? %></p>

		<hr/>

		<h2><%= @comments.count %> Comments</h2>
		<%= render @comments %>
		<% if policy(@post).create? %>
			<hr/>
			<h4>New Comment</h4>
			<%= render partial: 'comments/form', locals: { topic: @topic, post: @post, comment: @comment } %>
		<% end %>
	</div>
	<div class="col-md-4">
		<% if policy(@post).edit? %>
			<%= link_to "Edit", edit_topic_post_path(@topic,@post), class: 'btn btn-success' %>
		<% end %>
		<% if policy(@post).destroy? %>
			<%= link_to "Delete Post", [@topic, @post], method: :delete, class: 'btn btn-danger', confirm: 'Are you sure you want to delete this post?' %>
		<% end %>

		<div>
			<h3><%= pluralize(@post.points, 'point') %></h3>
			<small>
				<%= pluralize(@post.up_votes, 'up vote') %>,
				<%= pluralize(@post.down_votes, 'down vote') %>
			</small>
		</div>
		<%= render partial: 'favorites/favorite', locals: { topic: @topic, post: @post } %>
	</div>
</div>