config/routes.rb
BloccitR4::Application.routes.draw do
  get "comments/new"
  devise_for :users
  resources :users, only: [:update]

  resources :topics do
  	resources :posts, except: [:index] do
  		resources :comments, only: [:create, :destroy]
             get '/up-vote' => 'votes#up_vote', as: :up_vote
             get '/down-vote' => 'votes#down_vote', as: :down_vote
             resources :favorites, only: [:create, :destroy]
  	end
  end

  match "about", to: 'welcome#about', via: :get

  root to: 'welcome#index'
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote."}

  after_save :update_post

  def up_vote?
  	value == 1
  end

  def down_vote?
  	value == -1
  end

  private

  def update_post
  	self.post.update_rank
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	before_filter :setup

	def up_vote
		update_vote(1)
		redirect_to :back
	end

	def down_vote
		update_vote(-1)
		redirect_to :back
	end

	private

	def setup
		@topic = Topic.find(params[:topic_id])
		@post = @topic.posts.find(params[:post_id])

		@vote = @post.votes.where(user_id: current_user.id).first
	end

	def update_vote(new_value)
		if @vote
			authorize @vote, :update?
			@vote.update_attribute(:value, new_value)
		else
			@vote = current_user.votes.create(value: new_value, post: @post)
			authorize @vote, :create?
			@vote.save
		end
	end
end

app/views/votes/_voter.html.erb
<% if policy(Vote.new).create? %>
	<div class="vote-arrows pull-left">
		<div><%= link_to " ", topic_post_up_vote_path(topic, post), class: "glyphicon glyphicon-chevron-up #{(current_user.voted(post) && current_user.voted(post).up_vote?) ? 'voted' : '' }  " %></div>
		<div><strong><%= post.points %></strong></div>
		<div><%= link_to " ", topic_post_down_vote_path(topic, post), class: "glyphicon glyphicon-chevron-down #{(current_user.voted(post) && current_user.voted(post).down_vote?) ? 'voted' : '' } " %></div>
	</div>
<% end %>